### ISSUE TITLE
商户版公众号支付微信参数错误

### ISSUE THREAD

**Issue by kiwiflydream** [foxinmy/weixin4j#93]
[微信接口地址](https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_1)
其中
> 子商户公众账号ID        	sub_appid
在项目中是 sub_id
涉及要更改的地方目前遇到如下几个

``` java
com.foxinmy.weixin4j.model.WeixinPayAccount
com.foxinmy.weixin4j.payment.mch.MerchantResult#subId
com.foxinmy.weixin4j.api.MchApi#createBaseRequestMap
com.foxinmy.weixin4j.api.MchApi#declareMerchant
```

**Comment by foxinmy** [comment]
感谢反馈，我将着日修正！发自网易邮箱大师
            在2016年08月27日 11:08，KIWI 写道:微信接口地址
其中


子商户公众账号ID           sub_appid
在项目中是 sub_id
涉及要更改的地方目前遇到如下几个


com.foxinmy.weixin4j.model.WeixinPayAccount
com.foxinmy.weixin4j.payment.mch.MerchantResult#subId
com.foxinmy.weixin4j.api.MchApi#createBaseRequestMap
com.foxinmy.weixin4j.api.MchApi#declareMerchant

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/foxinmy/weixin4j","title":"foxinmy/weixin4j","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/foxinmy/weixin4j"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"商户版公众号支付微信参数错误 (#93)"}],"action":{"name":"View Issue","url":"https://github.com/foxinmy/weixin4j/issues/93"}}}
